import { Project } from '../types';

/**
 * PROGETTI REALI DEL PORTFOLIO DI ALICE MELE
 * Tutti i progetti includono:
 * - Titolo, Categorie, Descrizione ufficiale fornita
 * - Percorso PDF originale in /public./projects/<slug>/project.pdf
 * - Thumbnail prima pagina ad alta definizione in /public./projects/<slug>/cover.jpg
 * - Tag di dettaglio per ricerca e filtri
 */
export const userProjects: Project[] = [
  {
    id: 'festival-cinema-africano',
    title: 'Festival di Cinema Africano di Verona – Corporate Identity',
    category: 'Brand Identity / Corporate Identity / Visual System',
    categories: ['Brand & Visual Identity'],
    categorySlug: 'brand-identity',
    tags: ['Brand Identity', 'Corporate Identity', 'Visual System', 'Materiali Coordinati'],
    description: "Progetto di corporate identity sviluppato per il Festival di Cinema Africano di Verona, con la definizione di un sistema visivo riconoscibile e applicabile su differenti supporti. L'identità combina logo, palette cromatica, tipografia ed elementi grafici modulari, declinati su materiali coordinati come carta intestata, buste e supporti di comunicazione istituzionale.",
    summary: 'Corporate identity e sistema visivo coordinato con declinazione su materiali cartacei e istituzionali.',
    cover: './projects/festival-cinema-africano/cover.jpg',
    coverImage: './projects/festival-cinema-africano/cover.jpg',
    pdf: './projects/festival-cinema-africano/project.pdf',
    galleryImages: ['./projects/festival-cinema-africano/cover.jpg'],
    featured: true,
    sizeSpan: 'large',
    palette: ['#7C3AED', '#F59E0B', '#10B981', '#1E1B4B']
  },
  {
    id: 'oltre-i-confini-editorial',
    title: 'Oltre i confini – Editorial Project',
    category: 'Editorial Design / Magazine Design',
    categories: ['Editorial Design'],
    categorySlug: 'editorial-design',
    tags: ['Editorial Design', 'Magazine Design', 'Infografica', 'CISL', 'Reportage'],
    description: "Progetto editoriale dedicato al tema delle migrazioni in Italia, sviluppato attraverso dati, approfondimenti e contenuti di carattere sociale. L'identità visiva utilizza una griglia editoriale rigorosa, tipografia ad alto contrasto e fotografia documentaristica, costruendo una gerarchia chiara tra titoli, testi e immagini lungo l'intera pubblicazione.",
    summary: 'Progetto editoriale su griglia modulare, dati statistici e reportage fotografico sul tema delle migrazioni.',
    cover: './projects/oltre-i-confini-editorial/cover.jpg',
    coverImage: './projects/oltre-i-confini-editorial/cover.jpg',
    pdf: './projects/oltre-i-confini-editorial/project.pdf',
    galleryImages: ['./projects/oltre-i-confini-editorial/cover.jpg'],
    featured: true,
    sizeSpan: 'wide',
    palette: ['#047857', '#111827', '#F3F4F6', '#D97706']
  },
  {
    id: 'velocita-e-movimento',
    title: 'Velocità e Movimento – Exhibition Poster',
    category: 'Poster Design / Exhibition Communication / Cultural Graphic Design',
    categories: ['Poster Design'],
    categorySlug: 'poster-design',
    tags: ['Poster Design', 'Exhibition Communication', 'Cultural Graphic Design', 'Futurismo', 'Tipografia Sperimentale'],
    description: "Progetto di poster design per una mostra dedicata al Futurismo, sviluppato mettendo al centro i concetti di dinamismo, energia e movimento. La composizione combina texture pittoriche, contrasti cromatici e una tipografia geometrica e strutturata, creando una gerarchia visiva netta tra titolo e informazioni dell'evento.",
    summary: 'Poster design per mostra sul Futurismo incentrato su energia cinetica, texture pittoriche e rigore geometrico.',
    cover: './projects/velocita-e-movimento/cover.jpg',
    coverImage: './projects/velocita-e-movimento/cover.jpg',
    pdf: './projects/velocita-e-movimento/project.pdf',
    galleryImages: ['./projects/velocita-e-movimento/cover.jpg'],
    sizeSpan: 'tall',
    palette: ['#DC2626', '#1E293B', '#F8FAFC', '#F59E0B']
  },
  {
    id: 'grande-piramide-egitto',
    title: "Grande Piramide d'Egitto – Menu Design",
    category: 'Menu Design / Print Design / Visual Identity',
    categories: ['Brand & Visual Identity'],
    categorySlug: 'brand-identity',
    tags: ['Menu Design', 'Print Design', 'Visual Identity', 'Pattern Design', 'Food & Beverage'],
    description: "Progetto di menu design per una pizzeria a tema egizio, sviluppato attraverso una struttura editoriale ordinata e una forte caratterizzazione visiva. La composizione combina gerarchie tipografiche, palette scura con accenti dorati e pattern ispirati ai geroglifici, organizzando un'elevata quantità di informazioni in maniera leggibile e coerente con l'identità del locale.",
    summary: "Struttura editoriale complessa e identità visiva con finiture dorate e geroglifici per pizzeria a tema egizio.",
    cover: './projects/grande-piramide-egitto/cover.jpg',
    coverImage: './projects/grande-piramide-egitto/cover.jpg',
    pdf: './projects/grande-piramide-egitto/project.pdf',
    galleryImages: ['./projects/grande-piramide-egitto/cover.jpg'],
    sizeSpan: 'wide',
    palette: ['#1C1917', '#CA8A04', '#FBBF24', '#78716C']
  },
  {
    id: 'oltre-i-confini-banconota',
    title: 'Oltre i confini – Creazione banconota',
    category: 'Graphic Design / Currency Design / Vector Illustration',
    categories: ['Brand & Visual Identity'],
    categorySlug: 'brand-identity',
    tags: ['Graphic Design', 'Currency Design', 'Vector Illustration', 'Pattern di Sicurezza', 'Multiculturalità'],
    description: "Progetto di currency design basato sulla reinterpretazione grafica della banconota come supporto di comunicazione visiva. La composizione combina illustrazioni vettoriali modulari, forme geometriche e un sistema cromatico coordinato, costruendo un linguaggio visivo capace di rappresentare diversità, identità e multiculturalità attraverso una struttura coerente e riconoscibile.",
    summary: 'Reinterpretazione grafica della banconota con illustrazioni vettoriali modulari e pattern geometrici di sicurezza.',
    cover: './projects/oltre-i-confini-banconota/cover.jpg',
    coverImage: './projects/oltre-i-confini-banconota/cover.jpg',
    pdf: './projects/oltre-i-confini-banconota/project.pdf',
    galleryImages: ['./projects/oltre-i-confini-banconota/cover.jpg'],
    sizeSpan: 'large',
    palette: ['#4338CA', '#06B6D4', '#E0E7FF', '#312E81']
  },
  {
    id: 'happy-xmas-night',
    title: 'Happy Xmas Night – Event Poster',
    category: 'Poster Design / Event Communication',
    categories: ['Poster Design'],
    categorySlug: 'poster-design',
    tags: ['Poster Design', 'Event Communication', 'Visual Communication', 'Nightlife', 'Fotomontaggio'],
    description: "Progetto di visual communication per un evento nightlife a tema natalizio, sviluppato attraverso una composizione ad alto impatto visivo e una palette calda e luminosa. Il layout combina fotomontaggio, tipografia gerarchica e gestione dei contrasti per mettere in evidenza headline, guest, data e informazioni dell'evento.",
    summary: 'Manifesto per evento nightlife con fotomontaggio dinamico, palette vibrante e gerarchia tipografica netta.',
    cover: './projects/happy-xmas-night/cover.jpg',
    coverImage: './projects/happy-xmas-night/cover.jpg',
    pdf: './projects/happy-xmas-night/project.pdf',
    galleryImages: ['./projects/happy-xmas-night/cover.jpg'],
    sizeSpan: 'regular',
    palette: ['#B91C1C', '#EA580C', '#FEF08A', '#0F172A']
  },
  {
    id: 'la-maestra-del-vetro',
    title: 'La maestra del vetro – Book Cover Design',
    category: 'Book Cover Design / Editorial Design / Illustration',
    categories: ['Editorial Design'],
    categorySlug: 'editorial-design',
    tags: ['Book Cover Design', 'Editorial Design', 'Illustration', 'Copertina Libraria', 'Dorso & Risguardi'],
    description: "Progetto di progettazione editoriale per una copertina libraria completa, sviluppata su prima, quarta di copertina e dorso. Il visual combina illustrazione, composizione tipografica e una palette cromatica ispirata all'ambiente marino, costruendo un'identità coerente con il tono narrativo del romanzo.",
    summary: 'Progettazione editoriale completa di copertina libraria (prima, dorso e quarta) con illustrazione tematica.',
    cover: './projects/la-maestra-del-vetro/cover.jpg',
    coverImage: './projects/la-maestra-del-vetro/cover.jpg',
    pdf: null,
    galleryImages: ['./projects/la-maestra-del-vetro/cover.jpg'],
    sizeSpan: 'wide',
    palette: ['#0284C7', '#0369A1', '#E0F2FE', '#0C4A6E']
  },
  {
    id: 'percezione-social-awareness',
    title: 'Percezione – Social Awareness Poster',
    category: 'Poster Design / Social Communication / Visual Concept',
    categories: ['Poster Design'],
    categorySlug: 'poster-design',
    tags: ['Poster Design', 'Social Communication', 'Visual Concept', 'Inclusione Lavorativa', 'CISL'],
    description: "Progetto di comunicazione visiva a carattere sociale dedicato alla percezione del fenomeno migratorio nel contesto lavorativo. Il concept utilizza forme essenziali, contrasto figura-sfondo e gerarchia tipografica per rappresentare graficamente i temi dell'inclusione e della diversità attraverso un messaggio immediato e riconoscibile.",
    summary: "Poster di comunicazione sociale con contrasto figura-sfondo e sintesi grafica sul tema dell'inclusione lavorativa.",
    cover: './projects/percezione-social-awareness/cover.jpg',
    coverImage: './projects/percezione-social-awareness/cover.jpg',
    pdf: './projects/percezione-social-awareness/project.pdf',
    galleryImages: ['./projects/percezione-social-awareness/cover.jpg'],
    sizeSpan: 'tall',
    palette: ['#2563EB', '#1D4ED8', '#F1F5F9', '#0F172A']
  },
  {
    id: 'otium-art-newspaper',
    title: 'Otium – Art Newspaper Design',
    category: 'Editorial Design / Newspaper Layout / Cultural Publication',
    categories: ['Editorial Design', 'Typography & Lettering'],
    categorySlug: 'editorial-design',
    tags: ['Editorial Design', 'Newspaper Layout', 'Cultural Publication', 'Arte & Critica', 'Griglia a Colonne'],
    description: "Progetto di impaginazione editoriale in stile newspaper dedicato all'arte e alla divulgazione culturale. La composizione utilizza griglie a colonne, gerarchie tipografiche, citazioni in evidenza e un'alternanza calibrata tra testo e immagini, costruendo una pagina ricca di contenuti ma ordinata e leggibile.",
    summary: "Layout editoriale in stile newspaper con griglie a colonne serrate, citazioni in evidenza e cura tipografica.",
    cover: './projects/otium-art-newspaper/cover.jpg',
    coverImage: './projects/otium-art-newspaper/cover.jpg',
    pdf: './projects/otium-art-newspaper/project.pdf',
    galleryImages: ['./projects/otium-art-newspaper/cover.jpg'],
    sizeSpan: 'large',
    palette: ['#27272A', '#E4E4E7', '#7C3AED', '#52525B']
  },
  {
    id: 'rockwell-type-specimen',
    title: 'Rockwell – Type Specimen Poster',
    category: 'Typography / Type Specimen / Poster Design',
    categories: ['Typography & Lettering', 'Poster Design'],
    categorySlug: 'typography',
    tags: ['Typography', 'Type Specimen', 'Poster Design', 'Slab Serif', 'Monolineare', 'Anatomia del Carattere'],
    description: "Progetto di type specimen dedicato al carattere tipografico Rockwell, sviluppato per raccontarne origine, struttura e principali caratteristiche formali. La composizione mette in risalto costruzione monolineare, grazie slab serif, proporzioni e set di glifi attraverso una gerarchia tipografica dinamica e un uso controllato del colore.",
    summary: 'Tavola di type specimen dedicata alla struttura monolineare, alle grazie slab serif e ai glifi di Rockwell.',
    cover: './projects/rockwell-type-specimen/cover.jpg',
    coverImage: './projects/rockwell-type-specimen/cover.jpg',
    pdf: './projects/rockwell-type-specimen/project.pdf',
    galleryImages: ['./projects/rockwell-type-specimen/cover.jpg'],
    sizeSpan: 'tall',
    palette: ['#0284C7', '#1E293B', '#F8FAFC', '#64748B']
  },
  {
    id: 'photo-stories',
    title: 'Photo Stories – Editorial Photography Book',
    category: 'Editorial Design / Photo Book / Layout Design',
    categories: ['Editorial Design'],
    categorySlug: 'editorial-design',
    tags: ['Editorial Design', 'Photo Book', 'Layout Design', 'Fotografia Editoriale', 'Narrazione Visiva'],
    description: "Progetto di impaginazione editoriale per un libretto fotografico multipagina, sviluppato attraverso un sistema grafico coerente e flessibile. Il layout alterna immagini a pieno formato, composizioni modulari e blocchi testuali, lavorando su ritmo, proporzioni e gerarchia visiva per valorizzare la narrazione fotografica.",
    summary: 'Libretto fotografico multipagina con alternanza di immagini a piena pagina, ritmi visivi e gabbia editoriale dinamica.',
    cover: './projects/photo-stories/cover.jpg',
    coverImage: './projects/photo-stories/cover.jpg',
    pdf: './projects/photo-stories/project.pdf',
    galleryImages: ['./projects/photo-stories/cover.jpg'],
    sizeSpan: 'wide',
    palette: ['#18181B', '#A1A1AA', '#FAFAFA', '#6D28D9']
  },
  {
    id: 'ottobre-1917',
    title: 'Ottobre 1917 – Historical Event Poster',
    category: 'Poster Design / Cultural Communication / Historical Graphic Design',
    categories: ['Poster Design'],
    categorySlug: 'poster-design',
    tags: ['Poster Design', 'Cultural Communication', 'Historical Graphic Design', 'Rivoluzione Russa', 'Composizione Radiale'],
    description: "Progetto di poster design a tema storico-culturale dedicato alla Rivoluzione Russa. Il visual richiama l'estetica della propaganda sovietica attraverso una palette calda e fortemente contrastata, illustrazioni dal carattere monumentale e una composizione radiale che enfatizza tensione, energia e mobilitazione.",
    summary: 'Poster storico-culturale con richiami all’avanguardia costruttivista sovietica, contrasti netti e struttura radiale.',
    cover: './projects/ottobre-1917/cover.jpg',
    coverImage: './projects/ottobre-1917/cover.jpg',
    pdf: './projects/ottobre-1917/project.pdf',
    galleryImages: ['./projects/ottobre-1917/cover.jpg'],
    sizeSpan: 'regular',
    palette: ['#DC2626', '#991B1B', '#F59E0B', '#1C1917']
  },
  {
    id: 'buon-natale-lettering',
    title: 'Buon Natale – Lettering Poster',
    category: 'Lettering / Poster Design / Seasonal Communication',
    categories: ['Typography & Lettering', 'Poster Design'],
    categorySlug: 'lettering',
    tags: ['Lettering', 'Poster Design', 'Seasonal Communication', 'Calligrafia', 'Custom Typography'],
    description: "Progetto di lettering illustrato a tema natalizio, costruito integrando il messaggio tipografico all'interno della forma di una decorazione. Il visual punta su calligrafia personalizzata, equilibrio compositivo e contrasto cromatico, trasformando il testo nell'elemento grafico protagonista.",
    summary: 'Lettering calligrafico personalizzato sagomato a decorazione natalizia con forte equilibrio tipografico e cromatico.',
    cover: './projects/buon-natale-lettering/cover.jpg',
    coverImage: './projects/buon-natale-lettering/cover.jpg',
    pdf: './projects/buon-natale-lettering/project.pdf',
    galleryImages: ['./projects/buon-natale-lettering/cover.jpg'],
    sizeSpan: 'tall',
    palette: ['#059669', '#DC2626', '#FBBF24', '#FFFFFF']
  }
];
